-- Run this whole file once in Supabase Dashboard → SQL Editor.
create table if not exists public.site_content (
  id integer primary key check (id = 1),
  content jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

insert into public.site_content (id, content)
values (1, '{"schoolName":"राजकीय उच्च माध्यमिक विद्यालय, घातला","location":"घातला, राजस्थान","udise":"विद्यालय यू-डाइस कोड: अद्यतन किया जाना है","principal":"प्रधानाचार्य महोदय","phone":"विद्यालय कार्यालय से संपर्क करें","email":"admin@gsssghatla.edu.in","address":"राजकीय उच्च माध्यमिक विद्यालय, घातला, राजस्थान","about":"राजकीय उच्च माध्यमिक विद्यालय, घातला विद्यार्थियों को गुणवत्तापूर्ण, समावेशी एवं संस्कारयुक्त शिक्षा प्रदान करने के लिए प्रतिबद्ध है।","principalMessage":"हमारा प्रयास है कि प्रत्येक विद्यार्थी अपनी क्षमता को पहचाने और नैतिक मूल्यों के साथ आगे बढ़े।","admissionText":"नवीन प्रवेश के लिए विद्यालय कार्यालय से संपर्क करें।","notices":[{"id":"1","title":"सत्र 2026–27 हेतु नवीन प्रवेश संबंधी सूचना","date":"29 अगस्त 2026","important":true}],"activities":["प्रार्थना सभा एवं नैतिक शिक्षा","खेलकूद एवं योग गतिविधियाँ"],"gallery":[]}')
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('school-media', 'school-media', true)
on conflict (id) do update set public = true;

-- School portal tables. Supabase Auth stores passwords securely; these tables never store passwords.
create table if not exists public.school_users (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('student','teacher')),
  full_name text not null,
  email text not null unique,
  class_name text,
  roll_number text,
  employee_id text,
  subject text,
  created_at timestamptz not null default now()
);

create table if not exists public.homework (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  subject text not null,
  class_name text not null,
  due_date date,
  attachment_url text,
  teacher_id uuid references public.school_users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.school_users(id) on delete cascade,
  attendance_date date not null,
  status text not null check (status in ('present','absent','late','leave')),
  marked_by uuid references public.school_users(id) on delete set null,
  note text,
  created_at timestamptz not null default now(),
  unique(student_id, attendance_date)
);

create table if not exists public.gallery_items (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  event_date date,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.staff_posts (
  id bigint generated by default as identity primary key,
  full_name text not null,
  designation text not null,
  subject text,
  qualification text,
  photo_url text,
  display_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Private student master data. Only operational fields are retained from Shala Darpan exports.
-- Sensitive fields such as Aadhaar, parent mobile, address, DOB, income and category are intentionally excluded.
create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  sr_no text not null unique,
  full_name text not null,
  class_name text not null,
  section text,
  roll_number text,
  admission_date date,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists students_class_idx on public.students(class_name, section, roll_number);

alter table public.school_users enable row level security;
alter table public.homework enable row level security;
alter table public.attendance enable row level security;
alter table public.gallery_items enable row level security;
alter table public.staff_posts enable row level security;
alter table public.students enable row level security;

-- Browser access is intentionally disabled. Server routes use the service-role key.
