"use client";
import { useEffect,useState } from "react";
import styles from "../portal.module.css";

type Student={id:string;full_name:string;class_name:string|null;roll_number:string|null};
type Homework={id:number;title:string;description:string;subject:string;class_name:string;due_date:string|null};
export default function TeacherPanel(){const [students,setStudents]=useState<Student[]>([]);const [homework,setHomework]=useState<Homework[]>([]);const [msg,setMsg]=useState("");const [hw,setHw]=useState({title:"",description:"",subject:"",className:"",dueDate:""});const [att,setAtt]=useState({studentId:"",attendanceDate:new Date().toISOString().slice(0,10),status:"present",note:""});
async function load(){const [s,h]=await Promise.all([fetch("/api/portal/students",{credentials:"include"}),fetch("/api/portal/homework",{credentials:"include"})]);if(s.ok)setStudents((await s.json()).items);if(h.ok)setHomework((await h.json()).items)}useEffect(()=>{load()},[]);
async function addHomework(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/portal/homework",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify(hw)});const d=await r.json();setMsg(r.ok?"गृहकार्य प्रकाशित हो गया।":d.error||"त्रुटि");if(r.ok){setHw({title:"",description:"",subject:"",className:"",dueDate:""});load()}}
async function mark(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/portal/attendance",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify(att)});const d=await r.json();setMsg(r.ok?"उपस्थिति सुरक्षित हो गई।":d.error||"त्रुटि")}
return <div className={styles.main}><h1>शिक्षक डैशबोर्ड</h1><p className={styles.muted}>गृहकार्य प्रकाशित करें और विद्यार्थियों की दैनिक उपस्थिति दर्ज करें।</p><div className={styles.cards}><div className={styles.stat}><small>विद्यार्थी</small><b>{students.length}</b></div><div className={styles.stat}><small>गृहकार्य</small><b>{homework.length}</b></div><div className={styles.stat}><small>आज</small><b>{new Date().toLocaleDateString("hi-IN")}</b></div></div>{msg&&<div className={styles.success}>{msg}</div>}<section className={styles.panel}><h2>दैनिक उपस्थिति</h2><form className={styles.form} onSubmit={mark}><div className={styles.two}><label>विद्यार्थी<select value={att.studentId} onChange={e=>setAtt({...att,studentId:e.target.value})} required><option value="">विद्यार्थी चुनें</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name} — {s.class_name||""} {s.roll_number?`(${s.roll_number})`:""}</option>)}</select></label><label>तारीख<input type="date" value={att.attendanceDate} onChange={e=>setAtt({...att,attendanceDate:e.target.value})}/></label></div><div className={styles.two}><label>स्थिति<select value={att.status} onChange={e=>setAtt({...att,status:e.target.value})}><option value="present">उपस्थित</option><option value="absent">अनुपस्थित</option><option value="late">विलंब से</option><option value="leave">अवकाश</option></select></label><label>टिप्पणी<input value={att.note} onChange={e=>setAtt({...att,note:e.target.value})}/></label></div><button className={styles.button}>उपस्थिति सेव करें</button></form></section><section className={styles.panel}><h2>नया गृहकार्य</h2><form className={styles.form} onSubmit={addHomework}><label>शीर्षक<input required value={hw.title} onChange={e=>setHw({...hw,title:e.target.value})}/></label><label>विवरण<textarea required value={hw.description} onChange={e=>setHw({...hw,description:e.target.value})}/></label><div className={styles.two}><label>विषय<input required value={hw.subject} onChange={e=>setHw({...hw,subject:e.target.value})}/></label><label>कक्षा<input required value={hw.className} onChange={e=>setHw({...hw,className:e.target.value})}/></label></div><label>अंतिम तिथि<input type="date" value={hw.dueDate} onChange={e=>setHw({...hw,dueDate:e.target.value})}/></label><button className={`${styles.button} ${styles.alt}`}>गृहकार्य प्रकाशित करें</button></form></section></div>}
